package ytdlp

type Audio string

type Filename string

type Flag string

const (
	AudioAAC    Audio = "aac"
	AudioALAC   Audio = "alac"
	AudioFLAC   Audio = "flac"
	AudioM4A    Audio = "m4a"
	AudioMP3    Audio = "mp3"
	AudioOPUS   Audio = "opus"
	AudioVORBIS Audio = "vorbis"
	AudioWAV    Audio = "wav"

	FilenameTitle         Filename = "%(title)s.%(ext)s"
	FilenameUploaderTitle Filename = "%(uploader)s_%(title)s.%(ext)s"

	FlagHelp                        Flag = "-h"
	FlagVersion                     Flag = "--version"
	FlagUpdate                      Flag = "-U"
	FlagIgnoreErrors                Flag = "-i"
	FlagNoAbortOnError              Flag = "--no-abort-on-error"
	FlagAbortOnError                Flag = "--abort-on-error"
	FlagDumpUserAgent               Flag = "--dump-user-agent"
	FlagListExtractors              Flag = "--list-extractors"
	FlagExtractorArgs               Flag = "--extractor-args"
	FlagExtractorOptions            Flag = "--extractor-descriptions"
	FlagFlatPlaylist                Flag = "--flat-playlist"
	FlagNoPlaylist                  Flag = "--no-playlist"
	FlagYesPlaylist                 Flag = "--yes-playlist"
	FlagSkipUnavailableFragments    Flag = "--skip-unavailable-fragments"
	FlagAbortOnUnavailableFragments Flag = "--abort-on-unavailable-fragments"
	FlagKeepFragments               Flag = "--keep-fragments"
	FlagLazyPlaylist                Flag = "--lazy-playlist"
	FlagRestrictFilenames           Flag = "--restrict-filenames"
	FlagWindowsFilenames            Flag = "--windows-filenames"
	FlagWriteThumbnail              Flag = "--write-thumbnail"
	FlagWriteAllThumbnails          Flag = "--write-all-thumbnails"
	FlagListThumbnails              Flag = "--list-thumbnails"
	FlagQuiet                       Flag = "-q"
	FlagIgnoreWarnings              Flag = "--no-warnings"
	FlagSimulate                    Flag = "-s"
	FlagNoSimulate                  Flag = "--no-simulate"
	FlagSkipDownload                Flag = "--skip-download"
	FlagDumpJson                    Flag = "-j"
	FlagDumpSingleJson              Flag = "-J"
	FlagNewLine                     Flag = "--newline"
	FlagNoProgress                  Flag = "--no-progress"
	FlagProgress                    Flag = "--progress"
	FlagConsoleTitle                Flag = "--console-title"
	FlagVerbose                     Flag = "-v"
	FlagExtractAudio                Flag = "-x"
	FlagEmbedThumbnail              Flag = "--embed-thumbnail"
	FlagEmbedMetadata               Flag = "--embed-metadata"
	FlagNoDownloadArchive           Flag = "--no-download-archive"
	FlagConfigLocations             Flag = "--config-locations"
	FlagPluginDirs                  Flag = "--plugin-dirs"
	FlagDownloadArchive             Flag = "--download-archive"
	FlagBatchFile                   Flag = "-a"
	FlagLoadInfoJson                Flag = "--load-info-json"
	FlagCookieFile                  Flag = "--cookies"
	FlagCacheDir                    Flag = "--cache-dir"
	FlagFfmpegLocation              Flag = "--ffmpeg-location"
	FlagProgressTemplate            Flag = "--progress-template"
	FlagFilenameTemplate            Flag = "-o"
	FlagPrint                       Flag = "-O"
	FlagAudioQuality                Flag = "--audio-quality"
	FlagAudioFormat                 Flag = "--audio-format"
	FlagVideoFormat                 Flag = "--recode-video"
	FlagEncoding                    Flag = "--encoding"
	FlagPlaylistItems               Flag = "-I"
)
